library(openxlsx)
library(lubridate)
library(RCurl)
Day<-format(Sys.Date()-1,format="%d")
Month<-format(Sys.Date()-1,format="%m")
Year<-format(Sys.Date()-1,format="%Y")
Date<-paste(Year,Month,Day,sep="")
ftpUpload(paste("data/Payment_Collection_CASHLOAN_",Date,".csv",sep=""), paste("ftp://ngejmair:Fofawubian369@ftp.fofawubian369.com/public_html/wp-content/uploads/2022/11/",paste("data/Payment_Collection_CASHLOAN_",Date,".csv",sep=""),sep=""))
