on:
  schedule:
    - cron:  '09 08 * * *'

name: Render my document

jobs:
  render:
    name: Render my document
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
         # Set-up R
      - name: Install packages
        run: |
         R -e 'install.packages("tidyverse")'
         R -e 'install.packages("rvest")'
         R -e 'install.packages("rvest")'
         R -e 'install.packages("bigrquery")'
         R -e 'install.packages("devtools")'
         R -e 'install.packages("dplyr")'
         R -e 'install.packages("readxl")'
         R -e 'install.packages("googlesheets4")'
         R -e 'install.packages("readr")'
         R -e 'install.packages("lubridate")'
         R -e 'install.packages("shinymanager")'
         R -e 'install.packages("DT")'
         R -e 'install.packages("mailR")'
         R -e 'install.packages("htmlTable")'
         R -e 'install.packages("formattable")'
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("docs/index.Rmd", output_format = "all")'
      - name: Commit results
        run: |
          git add docs/index*
          git commit -m 'Re-build my-document' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
